### ISSUE TITLE
Incorrect link in website

### ISSUE THREAD

**Issue by DarkWiiPlayer** [squaresapp/rawjs#4]
On the website, the button ["Check out Squares"](https://www.squaresapp.org/rawjs/#:~:text=and%20mobile%20apps.-,Check%20out%20Squares.,-Wisdom%20%3E%20Party%20Tricks) links to the [RawJS sample project](https://github.com/squaresapp/rawjs-sample) instead of the Squares home page.

**Comment by jlyons210** [comment]
Good call-out. I submitted [a PR](https://github.com/squaresapp/www.squaresapp.org/pull/1) to the website repo.
